port: 80
healthcheck:
  type: http
  http_path: /health

resources:
  request:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 200m
    memory: 200Mi

forward_logs: true
monitoring: true

websocket: true

## only external services
externalDns: hancock-dlt-broker
#SSL: true
