env: production
app:
  server:
    port: 80
  blockchain:
    eth:
      host: kst-hancock-ms-ganache-cli.blockchainhub-develop
  db:
    host: mongo.blockchainhub-develop
    database: hancock
    eth:
      database: hancock
      collection: smartcontracts