env: production
app:
  server:
    port: 80
  blockchain:
    ethereum:
      host: kst-hancock-ms-ganache-cli.blockchainhub-develop
  db:
    host: mongo.blockchainhub-develop
    database: hancock
    ethereum:
      database: hancock
      collection: smartcontracts