#%RAML 1.0
---
title: Hancock DLT Broker
version: v1
baseUri: https://hancock-dlt-broker-blockchain-develop.es/{version}
mediaType: application/json

documentation:
 - title: Summary
   content: !include README.md

securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.yml

/health:
  description: |
    Healthcheck.
  get:
    description: !include docs/get-healthcheck.md
    responses: !include responses/get-healthcheck.yml
